# Generated by Django 5.2.7 on 2025-11-05 18:17

import main_section.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('cover', models.ImageField(upload_to=main_section.models.cover_path)),
                ('link', models.CharField(max_length=200)),
            ],
        ),
    ]
