# Generated by Django 5.2.7 on 2025-11-05 18:32

import main_section.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_section', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manga',
            options={'verbose_name': 'Манга', 'verbose_name_plural': 'Манга'},
        ),
        migrations.AlterField(
            model_name='manga',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to=main_section.models.cover_path),
        ),
        migrations.AlterField(
            model_name='manga',
            name='link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
