# Generated by Django 5.2.7 on 2025-11-09 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_section', '0003_alter_manga_options_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manga',
            options={'verbose_name': 'Манга', 'verbose_name_plural': 'Манга'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Профили', 'verbose_name_plural': 'Профили'},
        ),
    ]
