# Generated by Django 5.2.7 on 2025-11-07 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_section', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobrole',
            options={'verbose_name': 'Роли'},
        ),
        migrations.AlterModelOptions(
            name='vacancy',
            options={'verbose_name': 'Вакансии'},
        ),
    ]
