# Generated by Django 5.2.7 on 2025-11-09 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_section', '0002_alter_comment_comment_content_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категории', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Комментарии', 'verbose_name_plural': 'Комментарии'},
        ),
        migrations.AlterModelOptions(
            name='like',
            options={'verbose_name': 'Лайки', 'verbose_name_plural': 'Лайки'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Посты', 'verbose_name_plural': 'Посты'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['tag_name'], 'verbose_name': 'Тэги', 'verbose_name_plural': 'Тэги'},
        ),
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='comment',
            name='dislike_count',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='comment',
            name='like_count',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
